# Generated by Django 4.0.4 on 2022-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='marital_status',
            field=models.CharField(choices=[('SOLTEIRA', 'Solteira'), ('NAMORANDO', 'Namorando'), ('CASADA', 'Casada')], default=False, max_length=64),
        ),
    ]
